### ISSUE TITLE
Converting json document containing null to model class

### ISSUE THREAD

**Issue by matekb** [salat/salat#113]
I have a model containing a Double in an Option:

`case class Model(foo: Option[Double])`

When I receive JSON objects that I want to convert into this model and the JSON objects contain:
````json
{
  foo: null
}
````

Then Salat throws the following MatchError. I would have expected this to be deserialised to None.
````
play.api.Application$$anon$1: Execution exception[[MatchError: null]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.0]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [play_2.10.jar:2.2.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [play_2.10.jar:2.2.0]
	at scala.Option.map(Option.scala:145) [scala-library-2.10.3.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:261) [play_2.10.jar:2.2.0]
Caused by: scala.MatchError: null
	at com.novus.salat.transformers.in.NumericToDouble$class.transform(Injectors.scala:314) ~[salat-core_2.10-1.9.4.jar:1.9.4]
	at com.novus.salat.transformers.in.package$$anon$8.transform(Injectors.scala:56) ~[salat-core_2.10-1.9.4.jar:1.9.4]
	at com.novus.salat.transformers.Transformer$$anonfun$1.apply(Transformer.scala:97) ~[salat-core_2.10-1.9.4.jar:1.9.4]
	at com.novus.salat.transformers.Transformer$$anonfun$1.apply(Transformer.scala:97) ~[salat-core_2.10-1.9.4.jar:1.9.4]
	at scala.Option.flatMap(Option.scala:170) [scala-library-2.10.3.jar:na]
	at com.novus.salat.transformers.Transformer.transform_$bang(Transformer.scala:97) ~[salat-core_2.10-1.9.4.jar:1.9.4]
````

The workaround is of course to make sure the JSON object does not contain the null value at all. But it would be much simpler to be able to automatically convert this into None.

**Comment by noahlz** [comment]
Triaging old issues: this one appears to be fixed in 1.9.9 and later.

By all means re-open if it is actually still an issue.
