### ISSUE TITLE
Log more details in case of deserialization problem.

### ISSUE THREAD

**Issue by slorber** [salat/salat#143]
This error occurs with Salat 1.9.5 (tried with 1.9.9: same). It is an enum deserialization problem.

It happens only in some given environment (our staging server + one of our devs), randomly after a server restart. The DB does not seem to be the problem because with the same DB in some other envs it always work. I've checked the field in question in the DB and did not notice anything weird. No value in Mongo that does not match an existing enum value.

So It's hard to know which is the problem. 

Somehow it's related to this Scala Enumeration.withName issue that does not provide enough information: https://github.com/scala/scala/pull/4229

But also it would be nice, in case of deserialization, to log the whole DBObject that could not be converted to case class. Or at least the _id if it exists, so that we can check the data and see if anything is wrong.

```
utils.Error: Technical error during request processing
	at utils.Error$.apply(Error.scala:13) ~[stample-web.stample-web-1.0.jar:1.0]
	at controllers.BaseController$$anonfun$controllers$BaseController$$transfornExceptionsToFailure$1$$anonfun$apply$1.applyOrElse(BaseController.scala:306) [stample-web.stample-web-1.0.jar:1.0]
	at controllers.BaseController$$anonfun$controllers$BaseController$$transfornExceptionsToFailure$1$$anonfun$apply$1.applyOrElse(BaseController.scala:301) [stample-web.stample-web-1.0.jar:1.0]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [org.scala-lang.scala-library-2.10.3.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [org.scala-lang.scala-library-2.10.3.jar:na]
	at scala.util.Try$.apply(Try.scala:161) [org.scala-lang.scala-library-2.10.3.jar:na]
	at scala.util.Failure.recover(Try.scala:185) [org.scala-lang.scala-library-2.10.3.jar:na]
	at controllers.BaseController$$anonfun$controllers$BaseController$$transfornExceptionsToFailure$1.apply(BaseController.scala:301) [stample-web.stample-web-1.0.jar:1.0]
	at controllers.BaseController$$anonfun$controllers$BaseController$$transfornExceptionsToFailure$1.apply(BaseController.scala:297) [stample-web.stample-web-1.0.jar:1.0]
	at controllers.BaseController$$anonfun$sr$1$1$$anonfun$apply$3$$anonfun$apply$4.apply(BaseController.scala:262) [stample-web.stample-web-1.0.jar:1.0]
	at controllers.BaseController$$anonfun$sr$1$1$$anonfun$apply$3$$anonfun$apply$4.apply(BaseController.scala:262) [stample-web.stample-web-1.0.jar:1.0]
	at integration.MDCHelper$.withUserInMDC(MDCHelper.scala:26) [stample-web.stample-web-1.0.jar:1.0]
	at controllers.BaseController$$anonfun$sr$1$1$$anonfun$apply$3.apply(BaseController.scala:261) [stample-web.stample-web-1.0.jar:1.0]
	at controllers.BaseController$$anonfun$sr$1$1$$anonfun$apply$3.apply(BaseController.scala:261) [stample-web.stample-web-1.0.jar:1.0]
	at scala.util.Try$.apply(Try.scala:161) [org.scala-lang.scala-library-2.10.3.jar:na]
	at controllers.BaseController$class.controllers$BaseController$$withUserRelatedRuntimeExceptions(BaseController.scala:313) [stample-web.stample-web-1.0.jar:1.0]
	at controllers.BaseController$$anonfun$sr$1$1.apply(BaseController.scala:260) [stample-web.stample-web-1.0.jar:1.0]
	at controllers.BaseController$$anonfun$sr$1$1.apply(BaseController.scala:253) [stample-web.stample-web-1.0.jar:1.0]
	at play.api.mvc.ActionBuilder$$anonfun$apply$10.apply(Action.scala:221) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.api.mvc.ActionBuilder$$anonfun$apply$10.apply(Action.scala:220) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at securesocial.core.SecureSocial$SecuredActionBuilder$$anonfun$2$$anonfun$apply$1.apply(SecureSocial.scala:117) [ws.securesocial.securesocial_2.10-2.1.3.jar:2.1.3]
	at securesocial.core.SecureSocial$SecuredActionBuilder$$anonfun$2$$anonfun$apply$1.apply(SecureSocial.scala:113) [ws.securesocial.securesocial_2.10-2.1.3.jar:2.1.3]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.3.jar:na]
	at securesocial.core.SecureSocial$SecuredActionBuilder$$anonfun$2.apply(SecureSocial.scala:113) [ws.securesocial.securesocial_2.10-2.1.3.jar:2.1.3]
	at securesocial.core.SecureSocial$SecuredActionBuilder$$anonfun$2.apply(SecureSocial.scala:112) [ws.securesocial.securesocial_2.10-2.1.3.jar:2.1.3]
	at scala.Option.flatMap(Option.scala:170) [org.scala-lang.scala-library-2.10.3.jar:na]
	at securesocial.core.SecureSocial$SecuredActionBuilder.invokeSecuredBlock(SecureSocial.scala:112) [ws.securesocial.securesocial_2.10-2.1.3.jar:2.1.3]
	at securesocial.core.SecureSocial$SecuredActionBuilder.invokeBlock(SecureSocial.scala:146) [ws.securesocial.securesocial_2.10-2.1.3.jar:2.1.3]
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:309) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at controllers.BaseController$$anonfun$controllers$BaseController$$AuthenticatedImpl$1.apply(BaseController.scala:243) [stample-web.stample-web-1.0.jar:1.0]
	at controllers.BaseController$$anonfun$controllers$BaseController$$AuthenticatedImpl$1.apply(BaseController.scala:231) [stample-web.stample-web-1.0.jar:1.0]
	at play.api.mvc.Action$.invokeBlock(Action.scala:357) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:309) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:109) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:109) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:18) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:108) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:107) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.3.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:107) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:100) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:481) [com.typesafe.play.play-iteratees_2.10-2.2.2.jar:2.2.2]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:481) [com.typesafe.play.play-iteratees_2.10-2.2.2.jar:2.2.2]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:517) [com.typesafe.play.play-iteratees_2.10-2.2.2.jar:2.2.2]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:517) [com.typesafe.play.play-iteratees_2.10-2.2.2.jar:2.2.2]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:493) [com.typesafe.play.play-iteratees_2.10-2.2.2.jar:2.2.2]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:493) [com.typesafe.play.play-iteratees_2.10-2.2.2.jar:2.2.2]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.3.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.3.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) [com.typesafe.akka.akka-actor_2.10-2.2.0.jar:2.2.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) [com.typesafe.akka.akka-actor_2.10-2.2.0.jar:2.2.0]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.3.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.3.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.3.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.3.jar:na]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_55]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_55]
	at com.novus.salat.transformers.in.EnumInflater$class.transform(Injectors.scala:521) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at com.novus.salat.transformers.in.package$$anon$51.transform(Injectors.scala:269) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at com.novus.salat.transformers.Transformer$$anonfun$1.apply(Transformer.scala:97) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at com.novus.salat.transformers.Transformer$$anonfun$1.apply(Transformer.scala:97) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at scala.Option.flatMap(Option.scala:170) [org.scala-lang.scala-library-2.10.3.jar:na]
	at com.novus.salat.transformers.Transformer.transform_$bang(Transformer.scala:97) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at com.novus.salat.Field.in_$bang(Field.scala:64) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at com.novus.salat.ConcreteGrater$$anonfun$5$$anonfun$apply$2.apply(Grater.scala:274) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at com.novus.salat.ConcreteGrater$$anonfun$5$$anonfun$apply$2.apply(Grater.scala:274) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at scala.Option.flatMap(Option.scala:170) [org.scala-lang.scala-library-2.10.3.jar:na]
	at com.novus.salat.ConcreteGrater$$anonfun$5.apply(Grater.scala:274) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at com.novus.salat.ConcreteGrater$$anonfun$5.apply(Grater.scala:259) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[org.scala-lang.scala-library-2.10.3.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[org.scala-lang.scala-library-2.10.3.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[org.scala-lang.scala-library-2.10.3.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) ~[org.scala-lang.scala-library-2.10.3.jar:na]
	at scala.collection.AbstractTraversable.map(Traversable.scala:105) ~[org.scala-lang.scala-library-2.10.3.jar:na]
	at com.novus.salat.ConcreteGrater.asObject(Grater.scala:259) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at com.novus.salat.transformers.in.DBObjectToInContext$class.transform0(Injectors.scala:397) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at com.novus.salat.transformers.in.DBObjectToInContext$class.transform(Injectors.scala:403) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at com.novus.salat.transformers.in.package$$anon$36.transform(Injectors.scala:273) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at com.novus.salat.transformers.Transformer$$anonfun$1.apply(Transformer.scala:97) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at com.novus.salat.transformers.Transformer$$anonfun$1.apply(Transformer.scala:97) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at scala.Option.flatMap(Option.scala:170) [org.scala-lang.scala-library-2.10.3.jar:na]
	at com.novus.salat.transformers.Transformer.transform_$bang(Transformer.scala:97) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at com.novus.salat.Field.in_$bang(Field.scala:64) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at com.novus.salat.ConcreteGrater$$anonfun$5$$anonfun$apply$2.apply(Grater.scala:274) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at com.novus.salat.ConcreteGrater$$anonfun$5$$anonfun$apply$2.apply(Grater.scala:274) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at scala.Option.flatMap(Option.scala:170) [org.scala-lang.scala-library-2.10.3.jar:na]
	at com.novus.salat.ConcreteGrater$$anonfun$5.apply(Grater.scala:274) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at com.novus.salat.ConcreteGrater$$anonfun$5.apply(Grater.scala:259) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[org.scala-lang.scala-library-2.10.3.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[org.scala-lang.scala-library-2.10.3.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[org.scala-lang.scala-library-2.10.3.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) ~[org.scala-lang.scala-library-2.10.3.jar:na]
	at scala.collection.AbstractTraversable.map(Traversable.scala:105) ~[org.scala-lang.scala-library-2.10.3.jar:na]
	at com.novus.salat.ConcreteGrater.asObject(Grater.scala:259) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at com.novus.salat.dao.SalatMongoCursorBase$class.next(SalatMongoCursor.scala:45) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at com.novus.salat.dao.SalatMongoCursor.next(SalatMongoCursor.scala:156) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at scala.collection.Iterator$class.foreach(Iterator.scala:727) ~[org.scala-lang.scala-library-2.10.3.jar:na]
	at com.novus.salat.dao.SalatMongoCursor.foreach(SalatMongoCursor.scala:156) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48) ~[org.scala-lang.scala-library-2.10.3.jar:na]
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:176) ~[org.scala-lang.scala-library-2.10.3.jar:na]
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45) ~[org.scala-lang.scala-library-2.10.3.jar:na]
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273) ~[org.scala-lang.scala-library-2.10.3.jar:na]
	at com.novus.salat.dao.SalatMongoCursor.to(SalatMongoCursor.scala:156) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:257) ~[org.scala-lang.scala-library-2.10.3.jar:na]
	at com.novus.salat.dao.SalatMongoCursor.toList(SalatMongoCursor.scala:156) ~[com.novus.salat-core_2.10-1.9.5.jar:1.9.5]
	at services.impl.DefaultStampleServiceComponent$DefaultStampleService.getStampleTimeline(DefaultStampleServiceComponent.scala:438) ~[stample-web.stample-web-1.0.jar:1.0]
	at controllers.StamplesController$$anonfun$getStampleTimeline$1$$anonfun$apply$7.apply(StamplesController.scala:77) ~[stample-web.stample-web-1.0.jar:1.0]
	at controllers.StamplesController$$anonfun$getStampleTimeline$1$$anonfun$apply$7.apply(StamplesController.scala:77) ~[stample-web.stample-web-1.0.jar:1.0]
	at controllers.BaseController$class.timed(BaseController.scala:69) [stample-web.stample-web-1.0.jar:1.0]
	at controllers.StamplesController$.timed(StamplesController.scala:18) ~[stample-web.stample-web-1.0.jar:1.0]
	at controllers.StamplesController$$anonfun$getStampleTimeline$1.apply(StamplesController.scala:76) ~[stample-web.stample-web-1.0.jar:1.0]
	at controllers.StamplesController$$anonfun$getStampleTimeline$1.apply(StamplesController.scala:75) ~[stample-web.stample-web-1.0.jar:1.0]
	at controllers.BaseController$Ajax$$anonfun$AuthenticatedUserAction$1.apply(BaseController.scala:146) ~[stample-web.stample-web-1.0.jar:1.0]
	at controllers.BaseController$Ajax$$anonfun$AuthenticatedUserAction$1.apply(BaseController.scala:145) ~[stample-web.stample-web-1.0.jar:1.0]
	at controllers.BaseController$$anonfun$controllers$BaseController$$transfornExceptionsToFailure$1$$anonfun$apply$9.apply(BaseController.scala:299) ~[stample-web.stample-web-1.0.jar:1.0]
	at controllers.BaseController$$anonfun$controllers$BaseController$$transfornExceptionsToFailure$1$$anonfun$apply$9.apply(BaseController.scala:298) ~[stample-web.stample-web-1.0.jar:1.0]
	at scala.util.Try$.apply(Try.scala:161) [org.scala-lang.scala-library-2.10.3.jar:na]
	at controllers.BaseController$$anonfun$controllers$BaseController$$transfornExceptionsToFailure$1.apply(BaseController.scala:298) [stample-web.stample-web-1.0.jar:1.0]
	... 47 common frames omitted
Caused by: java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:313) ~[org.scala-lang.scala-library-2.10.3.jar:na]
	at scala.None$.get(Option.scala:311) ~[org.scala-lang.scala-library-2.10.3.jar:na]
	at scala.Enumeration.withName(Enumeration.scala:132) ~[org.scala-lang.scala-library-2.10.3.jar:na]
	at models.StampleType2.withName(Stample.scala) ~[stample-web.stample-web-1.0.jar:1.0]
	... 111 common frames omitted
```

**Comment by noahlz** [comment]
Greetings - I would suggest putting a try catch near the point in your code where the error is occurring, and logging the problematic case class there. Alternatively, please submit a pull request adding logging where you think appropriate.

**Comment by slorber** [comment]
@noahlz I can't do that in my application code.
Actually this happens when trying to iterating over a salat cursor which deserializes the items progressively.

For example calling `cursor.toList`

My point is that I would like to be able to identify inside the exception, for which item in the DB the exception occured. For now I can only know that my query returned an undeserializable object but I can't know which one easily.


I don't know enough Salat internals to make a PR but it seems according to the stacktrace that an appropriate place could be in `Grater.asObject` method:
https://github.com/novus/salat/blob/3612c7687fe628146eef49d56b620ca3ad68083c/salat-core/src/main/scala/com/novus/salat/Grater.scala#L293

**Comment by noahlz** [comment]
Seems like the more appropriate location is actually in the cursor list traversal. If someone is using `Grater.asObject` directly, then it makes sense handle and log the error there.

In the meantime, are you able to provide some example code that possible reproduces the error. Not necessary for your request, just curious.

**Comment by slorber** [comment]
Yes in the traversal would be fine too. However in `Grater.asObject` this permits the clients to avoid writting this try/catch. The aim here is to be able to identify productions problems easily in logs, without having to add debugging code and wait for next release to have useful error log.

My error has nothing really fancy. It's just trying to deserialize a DBO to a case class with an enum mapping.
The DBO simply has a field = "XXX" that does not match any of the Enum's declared Values.


The error I got from this problem does not indicate which of our Enums is causing this behavior (we use many for the same collection, but this is a Scala problem now fixed anyway), and does permit to know which DBO could not be unserialized (the point of this issue).
What I would like is to be able to easily identify the concerned DBO in logs without having to modify production code.

**Comment by noahlz** [comment]
After looking into this a bit more, `asObject` does in fact need a little more work. 

There is already code that handles this case and provides a more informative exception - but it is in the function `feedArgsToConstructor`. The code assumes that there will be no problems instantiating the case class's arguments, and the it will only blow up when passing those arguments into the case class constructor. 

Obviously - not always the case.

https://github.com/novus/salat/blob/3612c7687fe628146eef49d56b620ca3ad68083c/salat-core/src/main/scala/com/novus/salat/Grater.scala#L339

I think the best solution to create a custom exception, similar to the existing `ToObjectGlitch`, which is used a little further down in `Grater.scala`:

https://github.com/novus/salat/blob/c2b8dee550c59a4f586f6a4e692d00bd38bdaf7e/salat-core/src/main/scala/com/novus/salat/util/ToObjectGlitch.scala

Perhaps `ToObjectArgumentPreparationGlitch`?  Possible exception message:

```
    ${cause.getMessage}

    ${grater.toString} toObject failed on:
    SYM: ${sym.path}
    Field: $field

    FAILED TO DESERIALIZE:

    ${dbo.toString}

```

**Comment by slorber** [comment]
Yes that could be nice :)

**Comment by noahlz** [comment]
@slorber my life finally reached a point where I could start working on Salat again, and so I was able to have a look at this (FINALLY).  I know it's been over a year, but please have a look at #176.

If you can pull and test that branch, that would be ideal.  I am likely moving ahead with merging the PR and releasing in an upcoming `1.10.0-SNAPSHOT` unless you (or anybody else) have strong objections.

Thanks for your patience and look forward (hopefully!) to your input.

**Comment by noahlz** [comment]
This will be included in the next 1.10.x release (#176 merged)

**Comment by slorber** [comment]
I don't have much time to check that right now and I'll have to see if I can upgrade salat safely first, but thanks for this, it will certainly be helpful to me sooner or later :)

**Comment by noahlz** [comment]
Ok great - this is in `1.10.0-SNAPSHOT` for now.

I am likely not going to do the final release until the long holiday weekend (Sept 5).
