### ISSUE TITLE
Error with reason "Very strange!" - GRATER GLITCH

### ISSUE THREAD

**Issue by tacnoman** [salat/salat#167]
Hello guys.
I'm trying to use salat, but I cannot make anything. I'm getting this error (following the wiki `Annotation`)

```scala
Welcome to Scala version 2.10.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_65).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import com.mongodb.casbah.Imports._
import com.mongodb.casbah.Imports._

scala> import com.novus.salat._
import com.novus.salat._

scala> import com.novus.salat.global._
import com.novus.salat.global._

scala> import com.novus.salat.annotations._
import com.novus.salat.annotations._

scala> import com.novus.salat.annotations.raw.Persist
import com.novus.salat.annotations.raw.Persist

scala> case class Alpha(@Key("greeting") x: String)
defined class Alpha

scala> val a = Alpha(x = "Hello world")
a: Alpha = Alpha(Hello world)

scala> val dbo = grater[Alpha].asDBObject(a)
com.novus.salat.util.GraterGlitch:

      GRATER GLITCH - unable to find or instantiate a grater using supplied path name

      REASON: Very strange!  Path='Alpha' from pickled ScalaSig causes ClassNotFoundException

      Context: 'global'
      Path from pickled Scala sig: 'Alpha'



	at com.novus.salat.Context$class.lookup(Context.scala:213)
	at com.novus.salat.global.package$$anon$1.lookup(global.scala:29)
	at com.novus.salat.package$.grater(package.scala:62)
	at .<init>(<console>:23)
	at .<clinit>(<console>)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:734)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:983)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:604)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)
	at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:760)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:805)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:717)
	at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:581)
	at scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:588)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:591)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:882)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
	at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:837)
	at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:904)
	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:102)
	at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:77)
	at sbt.Console.sbt$Console$$console0$1(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:24)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:24)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:24)
	at sbt.Logger$$anon$4.apply(Logger.scala:90)
	at sbt.TrapExit$App.run(TrapExit.scala:244)
	at java.lang.Thread.run(Thread.java:745)


scala>
```

How can I do to solve this?
Thanks!

**Comment by noahlz** [comment]
Salat does not work in the Scala console in this manner, as it relies on compiled class files.

See: http://stackoverflow.com/a/34773627/7507

If you want to experiment with Salat, you could use a small sandbox project, like my https://github.com/noahlz/salat-examples

**Comment by noahlz** [comment]
See also: https://issues.scala-lang.org/browse/SI-4567
