### ISSUE TITLE
Weird case of ScalaSigParserError: Unexpected failure

### ISSUE THREAD

**Issue by manuelbernhardt** [salat/salat#19]
I managed to consistenly get the following stacktrace, even after a complete cleaning of the project:

    Caused by: scala.tools.scalap.scalax.rules.ScalaSigParserError: Unexpected failure
        at com.novus.salat.ConcreteGrater.typeRefType(Grater.scala:223)
        at com.novus.salat.ConcreteGrater$$anonfun$indexedFields$3.apply(Grater.scala:149)
        at com.novus.salat.ConcreteGrater$$anonfun$indexedFields$3.apply(Grater.scala:146)
        at com.novus.salat.ConcreteGrater.indexedFields(Grater.scala:146)
        at com.novus.salat.ConcreteGrater.iterateOut(Grater.scala:228)
        at com.novus.salat.ConcreteGrater.asDBObject(Grater.scala:244)
        at com.novus.salat.ConcreteGrater.asDBObject(Grater.scala:53)
        at com.novus.salat.dao.SalatDAO.insert(SalatDAO.scala:197)
        at com.novus.salat.dao.SalatDAO.insert(SalatDAO.scala:193)
        at controllers.organization.DataSetControl$.dataSetSubmit(DataSetControl.scala:55)

By simply adding a String field to a case class that would otherwise work like a charm. After some debugging I finally figured out that the culprit was the following member:

    indexingMappings: List[String] = List.empty[String]

After renaming it to `idxMappings` things started working again. Is this maybe some kind of reserved keyword somewhere? I have trouble thinking of another explanation.

I'm not quite sure if this issue report is useful, I thought I'd just send it in case it could help somebody.

**Comment by noahlz** [comment]
(Triaging old issues...)

@manuelbernhardt - if you're there, it looks like this one is no longer occurring in Scala 2.10+ / Salat 1.9.10+

If you ever figured out the story behind this one, I would love to hear it!
