### ISSUE TITLE
NoSuchMethodError: com.mongodb.casbah.MongoCollectionBase.find

### ISSUE THREAD

**Issue by Pyppe** [salat/salat#29]
Howdy!

I'm trying to use SalatDAO with Play! framework 2.0-RC2. But I cannot get the SalatDAO.find function to work:

<pre>
play.core.ActionInvoker$$anonfun$receive$1$$anon$1: Execution exception [[NoSuchMethodError: com.mongodb.casbah.MongoCollectionBase.find(Ljava/lang/Object;Ljava/lang/Object;Lscala/Function1;Lscala/Function1;)Ljava/lang/Object;]]
        at play.core.ActionInvoker$$anonfun$receive$1.apply(Invoker.scala:65) [play_2.9.1.jar:2.0-RC2]
        at play.core.ActionInvoker$$anonfun$receive$1.apply(Invoker.scala:46) [play_2.9.1.jar:2.0-RC2]
        at akka.actor.Actor$class.apply(Actor.scala:292) [akka-actor.jar:2.0-RC1]
        at play.core.ActionInvoker.apply(Invoker.scala:44) [play_2.9.1.jar:2.0-RC2]
        at akka.actor.ActorCell.invoke(ActorCell.scala:481) [akka-actor.jar:2.0-RC1]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:182) [akka-actor.jar:2.0-RC1]
Caused by: java.lang.NoSuchMethodError: com.mongodb.casbah.MongoCollectionBase.find(Ljava/lang/Object;Ljava/lang/Object;Lscala/Function1;Lscala/Function1;)Ljava/lang/Object;
        at com.novus.salat.dao.SalatDAO.find(SalatDAO.scala:321) ~[salat-core_2.9.1-0.0.8-SNAPSHOT.jar:0.0.8-SNAPSHOT]
        at com.novus.salat.dao.SalatDAO.find(SalatDAO.scala:323) ~[salat-core_2.9.1-0.0.8-SNAPSHOT.jar:0.0.8-SNAPSHOT]
        at controllers.Application$$anonfun$doStuff$1.apply(Application.scala:104) ~[classes/:2.0-RC2]
        at controllers.Application$$anonfun$doStuff$1.apply(Application.scala:94) ~[classes/:2.0-RC2]
        at play.api.mvc.Action$$anonfun$apply$4.apply(Action.scala:204) ~[play_2.9.1.jar:2.0-RC2]
        at play.api.mvc.Action$$anonfun$apply$4.apply(Action.scala:204) ~[play_2.9.1.jar:2.0-RC2]
</pre>

Code is the same as in https://github.com/novus/salat/wiki/SalatDAO: 

<pre>
package dao

import com.novus.salat._
import com.novus.salat.global._
import com.novus.salat.annotations._
import com.novus.salat.dao._
import com.mongodb.casbah.Imports._
import com.mongodb.casbah.MongoConnection

case class Alpha(@Key("_id") id: Int, x: String)
object AlphaDAO extends SalatDAO[Alpha, Int](collection = MongoConnection()("salat")("test_alpha"))
</pre>

Inserting / findOnById works, but not the "general query".

Is this a bug, or some issue of Salat/Play! combination?

Thanks! :)

**Comment by slorber** [comment]
@rktoomey I had similar issues but it seems that a sbt clean makes the problem disapear

Probably related to incremental compilation messing up

**Comment by noahlz** [comment]
Closing old issue. Please re-open if you are reading this and it looks like your issue, you have reproduction steps, and you can't resolve it with sbt clean.
